#!/bin/bash

if [ $# -ne 1 ]; then
    echo "complier_script <filename>"
    exit 1
fi

sed -i 's/\r$//' $1

filename=$(basename $1 .c)

cc="checkpatch.pl --file -no-tree $1"

s1=$($cc | grep "total" | cut -d "," -f1-2)
s2="total: 0 errors, 0 warnings"

if [ "$s1" = "$s2" ]; then
    gcc $1 -o $filename/output 2> ${filename}/error.txt #&& ${filename}/./output
else
    $cc > ${filename}/error.txt
fi
