#!/bin/bash

if [ $# -ne 1 ]; then
    echo "complier_script <filename>"
    exit 1
fi

checkpatch.pl --file -no-tree $1 3> checkpatch.txt

filename= ${1%.c} 
gcc $1 -o filename 2> error.txt && ./filename > output.txt

rm filename
